

post_install() {

mv /opt/trinity/share/icons/crystalsvg/128x128/apps/logo.png  /opt/trinity/share/icons/crystalsvg/128x128/apps/go.png
mv /opt/trinity/share/icons/crystalsvg/64x64/apps/logo.png /opt/trinity/share/icons/crystalsvg/64x64/apps/go.png
mv /opt/trinity/share/icons/crystalsvg/48x48/apps/logo.png /opt/trinity/share/icons/crystalsvg/48x48/apps/go.png
mv /opt/trinity/share/icons/crystalsvg/32x32/apps/logo.png /opt/trinity/share/icons/crystalsvg/32x32/apps/go.png
mv /opt/trinity/share/icons/crystalsvg/22x22/apps/logo.png /opt/trinity/share/icons/crystalsvg/22x22/apps/go.png
mv /opt/trinity/share/icons/crystalsvg/16x16/apps/logo.png /opt/trinity/share/icons/crystalsvg/16x16/apps/go.png
mv /opt/trinity/share/icons/crystalsvg/scalable/apps/logo.svgz /opt/trinity/share/icons/crystalsvg/scalable/go.svgz

mv /opt/trinity/share/icons/crystalsvg/128x128/apps/logo_k.png  /opt/trinity/share/icons/crystalsvg/128x128/apps/kmenu.png
mv /opt/trinity/share/icons/crystalsvg/64x64/apps/logo_k.png /opt/trinity/share/icons/crystalsvg/64x64/apps/kmenu.png
mv /opt/trinity/share/icons/crystalsvg/48x48/apps/logo_k.png /opt/trinity/share/icons/crystalsvg/48x48/apps/kmenu.png
mv /opt/trinity/share/icons/crystalsvg/32x32/apps/logo_k.png /opt/trinity/share/icons/crystalsvg/32x32/apps/kmenu.png
mv /opt/trinity/share/icons/crystalsvg/22x22/apps/logo_k.png /opt/trinity/share/icons/crystalsvg/22x22/apps/kmenu.png
mv /opt/trinity/share/icons/crystalsvg/16x16/apps/logo_k.png /opt/trinity/share/icons/crystalsvg/16x16/apps/kmenu.png
mv /opt/trinity/share/icons/crystalsvg/scalable/apps/logo_k.svgz /opt/trinity/share/icons/crystalsvg/scalable/kmenu.svgz

mv /opt/trinity/share/wallpapers/condres_tux.png /opt/trinity/share/wallpapers/Trinity4.png
mv /opt/trinity/share/wallpapers/condres_tux.svg /opt/trinity/share/wallpapers/Trinity-lineart.svg
}

post_upgrade() {
mv /opt/trinity/share/icons/crystalsvg/128x128/apps/logo.png  /opt/trinity/share/icons/crystalsvg/128x128/apps/go.png
mv /opt/trinity/share/icons/crystalsvg/64x64/apps/logo.png /opt/trinity/share/icons/crystalsvg/64x64/apps/go.png
mv /opt/trinity/share/icons/crystalsvg/48x48/apps/logo.png /opt/trinity/share/icons/crystalsvg/48x48/apps/go.png
mv /opt/trinity/share/icons/crystalsvg/32x32/apps/logo.png /opt/trinity/share/icons/crystalsvg/32x32/apps/go.png
mv /opt/trinity/share/icons/crystalsvg/22x22/apps/logo.png /opt/trinity/share/icons/crystalsvg/22x22/apps/go.png
mv /opt/trinity/share/icons/crystalsvg/16x16/apps/logo.png /opt/trinity/share/icons/crystalsvg/16x16/apps/go.png
mv /opt/trinity/share/icons/crystalsvg/scalable/apps/logo.svgz /opt/trinity/share/icons/crystalsvg/scalable/go.svgz
mv /opt/trinity/share/icons/crystalsvg/128x128/apps/logo_k.png  /opt/trinity/share/icons/crystalsvg/128x128/apps/kmenu.png
mv /opt/trinity/share/icons/crystalsvg/64x64/apps/logo_k.png /opt/trinity/share/icons/crystalsvg/64x64/apps/kmenu.png
mv /opt/trinity/share/icons/crystalsvg/48x48/apps/logo_k.png /opt/trinity/share/icons/crystalsvg/48x48/apps/kmenu.png
mv /opt/trinity/share/icons/crystalsvg/32x32/apps/logo_k.png /opt/trinity/share/icons/crystalsvg/32x32/apps/kmenu.png
mv /opt/trinity/share/icons/crystalsvg/22x22/apps/logo_k.png /opt/trinity/share/icons/crystalsvg/22x22/apps/kmenu.png
mv /opt/trinity/share/icons/crystalsvg/16x16/apps/logo_k.png /opt/trinity/share/icons/crystalsvg/16x16/apps/kmenu.png
mv /opt/trinity/share/icons/crystalsvg/scalable/apps/logo_k.svgz /opt/trinity/share/icons/crystalsvg/scalable/kmenu.svgz
mv /opt/trinity/share/wallpapers/condres_tux.svg /opt/trinity/share/wallpapers/Trinity-lineart.svg

}
 
