pre_install() {

rm -rf /usr/share/plymouth/themes/spinner_old 
rm -rf /usr/share/plymouth/themes/spinner_old1 
rm -rf /usr/share/plymouth/themes/spinfinity1 
rm -rf /usr/share/plymouth/themes/spinfinity 
rm -rf /usr/share/plymouth/themes/spinner 
rm -rf /usr/share/plymouth/themes/condres

}

post_install() {

ln -s /usr/share/plymouth/themes/condres* /usr/share/plymouth/themes/spinner
ln -s /usr/share/plymouth/themes/condres/* /usr/share/plymouth/themes/spinfinity
rm -rf /usr/share/plymouth/themes/spinner_old 
rm -rf /usr/share/plymouth/themes/spinner_old1 
rm -rf /usr/share/plymouth/themes/spinfinity1 
rm -rf /usr/share/plymouth/themes/spinfinity 
rm -rf /usr/share/plymouth/themes/spinner 
plymouth-set-default-theme -R condres
mkinitcpio -P

}

post_upgrade() {
rm -rf /usr/share/plymouth/themes/spinner_old 
rm -rf /usr/share/plymouth/themes/spinner_old1 
rm -rf /usr/share/plymouth/themes/spinfinity1 
rm -rf /usr/share/plymouth/themes/spinfinity 
rm -rf /usr/share/plymouth/themes/spinner 
ln -s /usr/share/plymouth/themes/condres* /usr/share/plymouth/themes/spinner
ln -s /usr/share/plymouth/themes/condres/* /usr/share/plymouth/themes/spinfinity
plymouth-set-default-theme -R condres
mkinitcpio -P

}

